env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  keyword-spacing:
    - error
    - after: true
  brace-style:
    - error
    - 1tbs
  comma-spacing:
    - error
    - after: true
  no-var:
    - error
